# Utilisation d'une image de base pour la déploiement de contenu statique
image: busybox

# Définition des étapes du pipeline
stages:
  - deploy

# Étape de déploiement sur GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Le site sera déployé à l'adresse $CI_PAGES_URL"
  artifacts:
    paths:
      - public  # Le dossier "public" contient les fichiers HTML, CSS, etc.
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Ne déploie que si c'est la branche principale (master/main)
