# Utilisation d'une image Node pour construire l'application React
image: node:16

# Définition des étapes du pipeline
stages:
  - build
  - deploy

# Étape de construction de l'application
build:
  stage: build
  script:
    # Installation des dépendances
    - npm install
    # Construction de l'application React
    - npm run build
  artifacts:
    paths:
      # Les fichiers construits qui seront utilisés pour le déploiement
      - build
  only:
    - main  # Ne construit que sur la branche principale (à adapter si nécessaire)

# Étape de déploiement sur GitLab Pages
pages:
  stage: deploy
  script:
    # Déplacement des fichiers du build vers le répertoire public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main  # Ne déploie que depuis la branche principale (à adapter si nécessaire)
